INSERT INTO `additional_charges` (`id`, `name`, `label`, `type`, `rate`, `status`, `min_order_amt`, `store_id`) VALUES
(NULL, 'Service Charges', 'Service Charges', 2, 10, 0, 1000, tblprfx_),
(NULL, 'Transportation Charges', 'Transportation Charges', 1, 100, 0, 500, tblprfx_);
INSERT INTO `cities` (`id`, `state_id`, `city_name`, `delivary_status`, `cod_status`, `status`, `store_id`) VALUES
(NULL, 1, 'Mumbai', 1, 1, 0, tblprfx_),
(NULL, 2, 'Ahemdabad', 1, 0, 1, tblprfx_),
(NULL, 1, 'Navi Mumbai', 1, 1, 1, tblprfx_);
INSERT INTO `couriers` (`id`, `name`, `url_key`, `details`, `pref`, `status`, `store_id`) VALUES
(NULL, 'Fedex India', 'fedex', '{\"key\":\"sdfsdf\",\"password\":\"sdfsdfsdf\",\"shipaccount\":\"sdfdfsdfsdf\",\"billaccount\":\"erwr\",\"dutyaccount\":\"dsdfsdf\",\"meter\":\"123456\",\"account_username\":\"test\",\"account_password\":\"7894566\"}', 1, 1, tblprfx_),
(NULL, 'Delhivery India', 'delhivery', '', 2, 1, tblprfx_),
(NULL, 'Blue Dart India', 'blue-dart', '', 3, 1, tblprfx_),
(NULL, 'Go Fetch Bangladesh', 'go-fetch', '', 4, 1, tblprfx_);
INSERT INTO `coupons` (`id`, `coupon_name`, `coupon_code`, `discount_type`, `coupon_value`, `initial_coupon_val`, `min_order_amt`, `coupon_type`, `coupon_image`, `coupon_desc`, `no_times_allowed`, `no_times_used`, `start_date`, `end_date`, `user_specific`, `allowed_per_user`, `restrict_to`, `status`, `store_id`, `created_by`, `updated_by`) VALUES
(NULL, 'New Store 50 Off', 'NEW50', 2, 50, 0, 500, 1, '', 'Use coupon code NEW50 to get 50 off on total cart value. Minimum order amount should be 500.', 1000, 20, '2018-01-01 00:00:00', '2020-12-31 00:00:00', 0, 0, 1, 1, tblprfx_, 0, 0);
INSERT INTO `email_template` (`id`, `url_key`, `name`, `subject`, `content`, `status`, `created_by`, `created_at`, `updated_by`, `updated_at`, `store_id`) VALUES
(NULL, 'registration', 'Register template', 'Registered Successfully', '<div style=\"max-width: 700px; min-width: 270px; margin: 0 auto; border: solid 2px #fff;\">\r\n<table style=\"padding: 15px; background-color: #[primary_color]; border-bottom: solid 5px #[secondary_color];\" border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\">\r\n<h1 style=\"color: #222; font-size: 23px; font-weight: 400; margin: 11px 13px 11px;\">Dear [firstName],</h1>\r\n</td>\r\n<td align=\"right\"><a href=\"[web_url]\" target=\"_blank\" rel=\"noopener\"><img src=\"[logoPath]\" /></a></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<div style=\"padding: 0px; font-family: Arial, Helvetica, sans-serif; color: #484848; font-size: 12px; line-height: 19px; height: auto;\">\r\n<div style=\"width: 100%; display: table;\">\r\n<div style=\"font-family: sans-serif; color: #333333; text-align: left; font-size: 13px;\">\r\n<h2>You are registered successfully!</h2>\r\n<h4 style=\"font-weight: normal;\">Welcome to the [storeName]! Now that you have created your account, you will be able to edit your account details, view your order history and discover vintage just by logging into your account. <br />[referralCode]</h4>\r\n</div>\r\n</div>\r\n<div style=\"padding: 20px 0px 0px 0px;\"><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">Regards,</strong><br /><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">[storeName]</strong></div>\r\n<br />\r\n<div style=\"font-family: sans-serif; color: #222; background: #ececec; padding: 12px; text-align: center; font-size: 13px; border-top: solid 1px #6b6b6b;\"><span style=\"font: Arial Black, Gadget, sans-serif;\">Visit Us <a style=\"color: #222;\" href=\"[web_url]\" target=\"_blank\" rel=\"noopener\">[web_url]</a></span></div>\r\n</div>\r\n</div>', 1, 1, '2016-07-11 17:59:04', 1, '2018-07-27 06:53:24', tblprfx_),
(NULL, 'order-success', 'Success template', 'Order has been placed successfully', '<div style="max-width: 700px; min-width: 270px; margin: 0 auto; border: solid 2px #fff;"><table style="padding: 15px; background-color: #[primary_color]; border-bottom: solid 5px #[secondary_color];" border="0" width="100%" cellspacing="0" cellpadding="0"><tbody><tr><td align="left"><h1 style="color: #222; font-size: 23px; font-weight: 400; margin: 11px 13px 11px;">Dear [firstName],</h1></td><td align="right"><a href="[web_url]" target="_blank" rel="noopener"><img src="[logoPath]" /></a></td></tr></tbody></table><div style="padding: 0px; font-family: Arial, Helvetica, sans-serif; color: #484848; font-size: 12px; line-height: 19px; height: auto;"><div style="width: 98%; display: table; margin: 0 auto;"><div style="font-family: sans-serif; color: #333333; text-align: left; font-size: 13px;"><h2>Thank you for placing order!</h2><h4 style="font-weight: normal;">Your order has been placed successfully!<br /><br /></h4></div></div><div style="font-family: sans-serif; color: #333333; text-align: center; font-size: 13px;"><h2 style="font: Arial Black,Gadget,sans-serif;">Order Details</h2></div><table style="font-family: arial,sans-serif; border-collapse: collapse; width: 98%; text-align: left; border: solid 2px #d2d2d2; margin: 0 auto 15px auto;"><tbody><tr style="text-align: center; padding: 8px; border-bottom: solid 1px #d2d2d2;"><th style="padding: 10px;">Order ID</th><th style="padding: 10px;">Order Date</th></tr><tr style="background: rgba(210,210,210,0.42); border-bottom: solid 1px #d2d2d2;"><td style="padding: 10px;" align="center" valign="top">[orderId]</td><td style="padding: 10px;" align="center" valign="top">[created_at]</td></tr></tbody></table>[invoice]<div style="padding: 20px 0px 0px 0px; width: 98%; margin: 0 auto;"><strong style="font-family: Source Sans Pro,Geneva,sans-serif;">Regards,</strong><br /><strong style="font-family: Source Sans Pro,Geneva,sans-serif;">[storeName]</strong></div><br /><div style="font-family: sans-serif; color: #222; background: #ececec; padding: 12px; text-align: center; font-size: 13px; border-top: solid 1px #6b6b6b;"><span style="font: \'Arial Black\', Gadget, sans-serif;">Visit Us <a style="color: #222;" href="[web_url]" target="_blank" rel="noopener">[web_url]</a></span></div></div></div>', 1, 0, '2018-07-26 07:32:32', 0, '2018-07-26 07:32:32', tblprfx_),
(NULL, 'forgot-password', 'Forgot Password', 'Forgot Password', '<div style=\"max-width: 700px; min-width: 270px; margin: 0 auto; border: solid 2px #fff;\">\r\n<table style=\"padding: 15px; background-color: #[primary_color]; border-bottom: solid 5px #[secondary_color];\" border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\">\r\n<h1 style=\"color: #222; font-size: 23px; font-weight: 400; margin: 11px 13px 11px;\">Dear [firstName],</h1>\r\n</td>\r\n<td align=\"right\"><a href=\"[web_url]\" target=\"_blank\" rel=\"noopener\"><img src=\"[logoPath]\" /></a></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<div style=\"padding: 0px; font-family: Arial, Helvetica, sans-serif; color: #484848; font-size: 12px; line-height: 19px; height: auto;\">\r\n<div style=\"width: 100%; display: table;\">\r\n<div style=\"font-family: sans-serif; color: #333333; text-align: left; font-size: 13px;\">\r\n<h4 style=\"font-weight: normal;\">We have received a request from you to reset your account password.</h4>\r\n<div style=\"padding: 0px 0px 0px 0px;\"><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\"><a href=\"[newlink]\" target=\"_blank\" rel=\"noopener\">Click here</a></strong> to reset your password.</div>\r\n</div>\r\n</div>\r\n<div style=\"padding: 20px 0px 0px 0px;\"><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">Regards,</strong><br /><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">[storeName]</strong></div>\r\n<br />\r\n<div style=\"font-family: sans-serif; color: #222; background: #ececec; padding: 12px; text-align: center; font-size: 13px; border-top: solid 1px #6b6b6b;\"><span style=\"font: \'Arial Black\', Gadget, sans-serif;\">Visit Us <a style=\"color: #222;\" href=\"[web_url]\" target=\"_blank\" rel=\"noopener\">[web_url]</a></span></div>\r\n</div>\r\n</div>', 1, 0, '2018-02-05 00:00:00', 0, '2018-07-26 07:57:38', tblprfx_),
(NULL, 'partial-shipping', 'Order Partially Shipped', 'Order Partially Shipped', '<div style=\"max-width: 700px; min-width: 270px; margin: 0 auto; border: solid 2px #fff;\">\r\n<table style=\"padding: 15px; background-color: #[primary_color]; border-bottom: solid 5px #[secondary_color];\" border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\">\r\n<h1 style=\"color: #222; font-size: 23px; font-weight: 400; margin: 11px 13px 11px;\">Dear [firstName],</h1>\r\n</td>\r\n<td align=\"right\"><a href=\"[web_url]\" target=\"_blank\" rel=\"noopener\"><img src=\"[logoPath]\" /></a></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<div style=\"padding: 0px; font-family: Arial, Helvetica, sans-serif; color: #484848; font-size: 12px; line-height: 19px; height: auto;\">\r\n<div style=\"width: 100%; display: table;\">\r\n<div style=\"font-family: sans-serif; color: #333333; text-align: left; font-size: 13px;\">\r\n	<h4 style=\"font-weight: normal;\"> Your Order  id:  [orderId] </h4>\r\n    <span>This email is to inform you that we are facing a slight delay in shipping out your complete order due to a slight operational glitch at our end. Your order has been partially shipped and we will be shipping theremaining order out in 2-3 days. You will be notified once your complete order has been shipped.  </span>\r\n	<br /><br />\r\n	<span> We are always striving to improve our services and make the whole experience of shopping with us even better. Any feedback from you would be extremely valuable to us and help us grow. Please feel free to drop us an email, call us, or get in touch with us on our various social media channels.  </span>\r\n</div>\r\n[invoice]\r\n</div>\r\n<br />\r\n<div style=\"padding: 20px 0px 0px 0px;\"><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">Regards,</strong><br /><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">[storeName]</strong></div>\r\n<br />\r\n<div style=\"font-family: sans-serif; color: #222; background: #ececec; padding: 12px; text-align: center; font-size: 13px; border-top: solid 1px #6b6b6b;\"><span style=\"font: \'Arial Black\', Gadget, sans-serif;\">Visit Us <a style=\"color: #222;\" href=\"[web_url]\" target=\"_blank\" rel=\"noopener\">[web_url]</a></span></div>\r\n</div>\r\n</div>', 1, 1, '2018-02-13 00:00:00', 0, '2018-02-13 12:14:31', tblprfx_),
(NULL, 'undelivered', 'Unelivered Order', 'Order Not Delivered', '<div style=\"max-width: 700px; min-width: 270px; margin: 0 auto; border: solid 2px #fff;\">\r\n<table style=\"padding: 15px; background-color: #[primary_color]; border-bottom: solid 5px #[secondary_color];\" border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\">\r\n<h1 style=\"color: #222; font-size: 23px; font-weight: 400; margin: 11px 13px 11px;\">Dear [firstName],</h1>\r\n</td>\r\n<td align=\"right\"><a href=\"[web_url]\" target=\"_blank\" rel=\"noopener\"><img src=\"[logoPath]\" /></a></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<div style=\"padding: 0px; font-family: Arial, Helvetica, sans-serif; color: #484848; font-size: 12px; line-height: 19px; height: auto;\">\r\n<div style=\"width: 100%; display: table;\">\r\n<div style=\"font-family: sans-serif; color: #333333; text-align: left; font-size: 13px;\">\r\n	<h4 style=\"font-weight: normal;\"> Your Order  id:  [orderId] </h4>\r\n    <span>This is regarding the order you placed with us. This is to inform you that your package was shipped out by us but could not be delivered by our courier partners. Please let us know if you would like us to ship your order out again.  </span>\r\n	<br /><br />\r\n	<span> We are always striving to improve our services and make the whole experience of shopping with us even better. Any feedback from you would be extremely valuable to us and help us grow. Please feel free to drop us an email, call us, or get in touch with us on our various social media channels.   </span>\r\n</div>\r\n[invoice]\r\n</div>\r\n<br />\r\n<div style=\"padding: 20px 0px 0px 0px;\"><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">Regards,</strong><br /><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">[storeName]</strong></div>\r\n<br />\r\n<div style=\"font-family: sans-serif; color: #222; background: #ececec; padding: 12px; text-align: center; font-size: 13px; border-top: solid 1px #6b6b6b;\"><span style=\"font: \'Arial Black\', Gadget, sans-serif;\">Visit Us <a style=\"color: #222;\" href=\"[web_url]\" target=\"_blank\" rel=\"noopener\">[web_url]</a></span></div>\r\n</div>\r\n</div>', 1, 0, '2018-02-13 00:00:00', 0, '2018-02-13 12:13:12', tblprfx_),
(NULL, 'return-order', 'Return Order', 'Order Return Request Processed', '<div style=\"max-width: 700px; min-width: 270px; margin: 0 auto; border: solid 2px #fff;\">\r\n<table style=\"padding: 15px; background-color: #[primary_color]; border-bottom: solid 5px #[secondary_color];\" border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\">\r\n<h1 style=\"color: #222; font-size: 23px; font-weight: 400; margin: 11px 13px 11px;\">Dear [firstName],</h1>\r\n</td>\r\n<td align=\"right\"><a href=\"[web_url]\" target=\"_blank\" rel=\"noopener\"><img src=\"[logoPath]\" /></a></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<div style=\"padding: 0px; font-family: Arial, Helvetica, sans-serif; color: #484848; font-size: 12px; line-height: 19px; height: auto;\">\r\n<div style=\"width: 100%; display: table;\">\r\n<div style=\"font-family: sans-serif; color: #333333; text-align: left; font-size: 13px;\">\r\n	<h4 style=\"font-weight: normal;\"> Your Order  id:  [orderId] </h4>\r\n    <span>This is to inform you that your order return request has been processed. Your refund will be credited to your store account as Reward Points which you can use for future purchases. </span>\r\n	<br /><br />\r\n	<span>We are always striving to improve our services and make the whole experience of shopping with us even better. Any feedback from you would be extremely valuable to us and help us grow. Please feel free to drop us an email, call us, or get in touch with us on our various social media channels. </span>\r\n</div>\r\n<br /><br />\r\n[invoice]\r\n</div>\r\n<br />\r\n<div style=\"padding: 20px 0px 0px 0px;\"><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">Regards,</strong><br /><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">[storeName]</strong></div>\r\n<br />\r\n<div style=\"font-family: sans-serif; color: #222; background: #ececec; padding: 12px; text-align: center; font-size: 13px; border-top: solid 1px #6b6b6b;\"><span style=\"font: \'Arial Black\', Gadget, sans-serif;\">Visit Us <a style=\"color: #222;\" href=\"[web_url]\" target=\"_blank\" rel=\"noopener\">[web_url]</a></span></div>\r\n</div>\r\n</div>', 1, 0, '2018-02-13 00:00:00', 0, '2018-03-07 10:05:42', tblprfx_),
(NULL, 'exchange-order', 'Order Exchange', 'Order Exchange Request Processed', '<div style=\"max-width: 700px; min-width: 270px; margin: 0 auto; border: solid 2px #fff;\">\r\n<table style=\"padding: 15px; background-color: #[primary_color]; border-bottom: solid 5px #[secondary_color];\" border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\">\r\n<h1 style=\"color: #222; font-size: 23px; font-weight: 400; margin: 11px 13px 11px;\">Dear [firstName],</h1>\r\n</td>\r\n<td align=\"right\"><a href=\"[web_url]\" target=\"_blank\" rel=\"noopener\"><img src=\"[logoPath]\" /></a></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<div style=\"padding: 0px; font-family: Arial, Helvetica, sans-serif; color: #484848; font-size: 12px; line-height: 19px; height: auto;\">\r\n<div style=\"width: 100%; display: table;\">\r\n<div style=\"font-family: sans-serif; color: #333333; text-align: left; font-size: 13px;\">\r\n	<h4 style=\"font-weight: normal;\"> Your Order  id:  [orderId] </h4>\r\n    <span>This is to inform you that your order exchange request has been processed and your order has been dispatched from our warehouse. </span>\r\n	<br /><br />\r\n	<span>Orders within India are delivered within 7 - 8 working days, and International orders are delivered within 10 to 15 working days. Delivery time may vary depending upon the shipping address. Please note that this is the maximum time for delivery.</span>\r\n	<br /><br />\r\n	<span>\r\n	We are always striving to improve our services and make the whole experience of shopping with us even better. Any feedback from you would be extremely valuable to us and help us grow. Please feel free to drop us an email, call us, or get in touch with us on our various social media channels.</span>\r\n</div>\r\n<br /><br />\r\n[invoice]\r\n</div>\r\n<br />\r\n<div style=\"padding: 20px 0px 0px 0px;\"><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">Regards,</strong><br /><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">[storeName]</strong></div>\r\n<br />\r\n<div style=\"font-family: sans-serif; color: #222; background: #ececec; padding: 12px; text-align: center; font-size: 13px; border-top: solid 1px #6b6b6b;\"><span style=\"font: \'Arial Black\', Gadget, sans-serif;\">Visit Us <a style=\"color: #222;\" href=\"[web_url]\" target=\"_blank\" rel=\"noopener\">[web_url]</a></span></div>\r\n</div>\r\n</div>', 1, 0, '2018-02-13 00:00:00', 0, '2018-02-13 12:10:03', tblprfx_),
(NULL, 'cancel-order','Order Cancelled', 'Your Order Has Been Cancelled', '<div style=\"max-width: 700px; min-width: 270px; margin: 0 auto; border: solid 2px #fff;\">\r\n<table style=\"padding: 15px; background-color: #[primary_color]; border-bottom: solid 5px #[secondary_color];\" border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\">\r\n<h1 style=\"color: #222; font-size: 23px; font-weight: 400; margin: 11px 13px 11px;\">Dear [firstName],</h1>\r\n</td>\r\n<td align=\"right\"><a href=\"[web_url]\" target=\"_blank\" rel=\"noopener\"><img src=\"[logoPath]\" /></a></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<div style=\"padding: 0px; font-family: Arial, Helvetica, sans-serif; color: #484848; font-size: 12px; line-height: 19px; height: auto;\">\r\n<div style=\"width: 100%; display: table;\">\r\n<div style=\"font-family: sans-serif; color: #333333; text-align: left; font-size: 13px;\">\r\n	<h4 style=\"font-weight: normal;\"> Your Order  id:  [orderId] </h4>\r\n    <span>This is to inform you that your request for order cancellation has been processed. If you have paid using a Credit/ Debit Card or Net Banking, your payment has been reversed and the amount should reflect in your account within 10 working days. </span>\r\n	<br /><br />\r\n	<span>We are always striving to improve our services and make the whole experience of shopping with us even better. Any feedback from you would be extremely valuable to us and help us grow. Please feel free to drop us an email, call us, or get in touch with us on our various social media channels.</span>\r\n	\r\n</div>\r\n<br /><br />\r\n[invoice]\r\n</div>\r\n<br />\r\n<div style=\"padding: 20px 0px 0px 0px;\"><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">Regards,</strong><br /><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">[storeName]</strong></div>\r\n<br />\r\n<div style=\"font-family: sans-serif; color: #222; background: #ececec; padding: 12px; text-align: center; font-size: 13px; border-top: solid 1px #6b6b6b;\"><span style=\"font: \'Arial Black\', Gadget, sans-serif;\">Visit Us <a style=\"color: #222;\" href=\"[web_url]\" target=\"_blank\" rel=\"noopener\">[web_url]</a></span></div>\r\n</div>\r\n</div>', 1, 0, '2018-02-13 06:00:00', 0, '2018-02-13 11:45:33', tblprfx_),
(NULL, 'refund-order', 'Order refund', 'Order Refund Request', '<div style=\"max-width: 700px; min-width: 270px; margin: 0 auto; border: solid 2px #fff;\">\r\n<table style=\"padding: 15px; background-color: #[primary_color]; border-bottom: solid 5px #[secondary_color];\" border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\">\r\n<h1 style=\"color: #222; font-size: 23px; font-weight: 400; margin: 11px 13px 11px;\">Dear [firstName],</h1>\r\n</td>\r\n<td align=\"right\"><a href=\"[web_url]\" target=\"_blank\" rel=\"noopener\"><img src=\"[logoPath]\" /></a></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<div style=\"padding: 0px; font-family: Arial, Helvetica, sans-serif; color: #484848; font-size: 12px; line-height: 19px; height: auto;\">\r\n<div style=\"width: 100%; display: table;\">\r\n<div style=\"font-family: sans-serif; color: #333333; text-align: left; font-size: 13px;\">\r\n	<h4 style=\"font-weight: normal;\"> Your Order  id:  [orderId] </h4>\r\n    <span>This is to inform you that your order refund request has been processed and the amount will reflect in your account within 10 working days. </span>\r\n	<br /><br />\r\n	<span>We are always striving to improve our services and make the whole experience of shopping with us even better. Any feedback from you would be extremely valuable to us and help us grow. Please feel free to drop us an email, call us, or get in touch with us on our various social media channels.</span>\r\n	\r\n</div>\r\n<br /><br />\r\n[invoice]\r\n</div>\r\n<br />\r\n<div style=\"padding: 20px 0px 0px 0px;\"><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">Regards,</strong><br /><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">[storeName]</strong></div>\r\n<br />\r\n<div style=\"font-family: sans-serif; color: #222; background: #ececec; padding: 12px; text-align: center; font-size: 13px; border-top: solid 1px #6b6b6b;\"><span style=\"font: \'Arial Black\', Gadget, sans-serif;\">Visit Us <a style=\"color: #222;\" href=\"[web_url]\" target=\"_blank\" rel=\"noopener\">[web_url]</a></span></div>\r\n</div>\r\n</div>', 1, 0, '2018-02-13 12:00:00', 0, '2018-02-13 11:43:08', tblprfx_),
(NULL, 'deliver-order', 'Order Delivered', 'Your Order Has Been Delivered', '<div style=\"max-width: 700px; min-width: 270px; margin: 0 auto; border: solid 2px #fff;\">\r\n<table style=\"padding: 15px; background-color: #[primary_color]; border-bottom: solid 5px #[secondary_color];\" border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\">\r\n<h1 style=\"color: #222; font-size: 23px; font-weight: 400; margin: 11px 13px 11px;\">Dear [firstName],</h1>\r\n</td>\r\n<td align=\"right\"><a href=\"[web_url]\" target=\"_blank\" rel=\"noopener\"><img src=\"[logoPath]\" /></a></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<div style=\"padding: 0px; font-family: Arial, Helvetica, sans-serif; color: #484848; font-size: 12px; line-height: 19px; height: auto;\">\r\n<div style=\"width: 100%; display: table;\">\r\n<div style=\"font-family: sans-serif; color: #333333; text-align: left; font-size: 13px;\">\r\n	<h4 style=\"font-weight: normal;\"> Your Order  id:  [orderId] </h4>\r\n    <span>This is to confirm that your order has been delivered. We hope you had a wonderful shopping experience and we hope to see you in the future.</span>\r\n	<br /><br />\r\n	<span>We are always striving to improve our services and make the whole experience of shopping with us even better. Any feedback from you would be extremely valuable to us and help us grow.</span>\r\n	\r\n</div>\r\n<br /><br />\r\n[invoice]\r\n</div>\r\n<br />\r\n<div style=\"padding: 20px 0px 0px 0px;\"><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">Regards,</strong><br /><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">[storeName]</strong></div>\r\n<br />\r\n<div style=\"font-family: sans-serif; color: #222; background: #ececec; padding: 12px; text-align: center; font-size: 13px; border-top: solid 1px #6b6b6b;\"><span style=\"font: \'Arial Black\', Gadget, sans-serif;\">Visit Us <a style=\"color: #222;\" href=\"[web_url]\" target=\"_blank\" rel=\"noopener\">[web_url]</a></span></div>\r\n</div>\r\n</div>', 1, 0, '2018-02-13 00:16:00', 0, '2018-02-13 11:45:54', tblprfx_),
(NULL, 'order-shipped', 'Order Shipped', 'Your Order Has Been Shipped', '<div style=\"max-width: 700px; min-width: 270px; margin: 0 auto; border: solid 2px #fff;\">\r\n<table style=\"padding: 15px; background-color: #[primary_color]; border-bottom: solid 5px #[secondary_color];\" border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\">\r\n<h1 style=\"color: #222; font-size: 23px; font-weight: 400; margin: 11px 13px 11px;\">Dear [firstName],</h1>\r\n</td>\r\n<td align=\"right\"><a href=\"[web_url]\" target=\"_blank\" rel=\"noopener\"><img src=\"[logoPath]\" /></a></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<div style=\"padding: 0px; font-family: Arial, Helvetica, sans-serif; color: #484848; font-size: 12px; line-height: 19px; height: auto;\">\r\n<div style=\"width: 100%; display: table;\">\r\n<div style=\"font-family: sans-serif; color: #333333; text-align: left; font-size: 13px;\">\r\n	<h4 style=\"font-weight: normal;\"> Your Order  id:  [orderId] </h4>\r\n     <span>This is to inform you that your order has been dispatched from our warehouse. Below is a table with the summary of your order.</span>\r\n	\r\n	\r\n</div>\r\n<br /><br />\r\n[invoice]\r\n</div>\r\n<br />\r\n<div style=\"padding: 20px 0px 0px 0px;\"><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">Regards,</strong><br /><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">[storeName]</strong></div>\r\n<br />\r\n<div style=\"font-family: sans-serif; color: #222; background: #ececec; padding: 12px; text-align: center; font-size: 13px; border-top: solid 1px #6b6b6b;\"><span style=\"font: \'Arial Black\', Gadget, sans-serif;\">Visit Us <a style=\"color: #222;\" href=\"[web_url]\" target=\"_blank\" rel=\"noopener\">[web_url]</a></span></div>\r\n</div>\r\n</div>', 1, 0, '2018-02-13 00:24:00', 0, '2018-02-13 00:00:00', tblprfx_),
(NULL, 'delay-in-shipment', 'Order Shipped Delay', 'Delay in Order Shipment', '<div style=\"max-width: 700px; min-width: 270px; margin: 0 auto; border: solid 2px #fff;\">\r\n<table style=\"padding: 15px; background-color: #[primary_color]; border-bottom: solid 5px #[secondary_color];\" border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\">\r\n<h1 style=\"color: #222; font-size: 23px; font-weight: 400; margin: 11px 13px 11px;\">Dear [firstName],</h1>\r\n</td>\r\n<td align=\"right\"><a href=\"[web_url]\" target=\"_blank\" rel=\"noopener\"><img src=\"[logoPath]\" /></a></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<div style=\"padding: 0px; font-family: Arial, Helvetica, sans-serif; color: #484848; font-size: 12px; line-height: 19px; height: auto;\">\r\n<div style=\"width: 100%; display: table;\">\r\n<div style=\"font-family: sans-serif; color: #333333; text-align: left; font-size: 13px;\">\r\n	<h4 style=\"font-weight: normal;\"> Your Order  id:  [orderId] </h4>\r\n    <span> This email is to inform you that we are facing a slight delay in shipping out your order due to a slight operational glitch at our end. We will be shipping your order out in 2-3 days and you will be notified once your order has been shipped. </span>\r\n	<br /><br />\r\n	<span> We are always striving to improve our services and make the whole experience of shopping with us even better. Any feedback from you would be extremely valuable to us and help us grow. Please feel free to drop us an email, call us, or get in touch with us on our various social media channels.  </span>\r\n</div>\r\n</div>\r\n<br />\r\n<div style=\"padding: 20px 0px 0px 0px;\"><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">Regards,</strong><br /><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">[storeName]</strong></div>\r\n<br />\r\n<div style=\"font-family: sans-serif; color: #222; background: #ececec; padding: 12px; text-align: center; font-size: 13px; border-top: solid 1px #6b6b6b;\"><span style=\"font: \'Arial Black\', Gadget, sans-serif;\">Visit Us <a style=\"color: #222;\" href=\"[web_url]\" target=\"_blank\" rel=\"noopener\">[web_url]</a></span></div>\r\n</div>\r\n</div>', 1, 0, '2018-02-13 08:25:00', 0, '2018-02-13 12:31:24', tblprfx_),
(NULL, 'contact-us', 'contact Us', 'Contact Us ', '<table style=\"border-collapse: collapse; width: 100%;\" border=\"1\">\r\n<tbody>\r\n<tr>\r\n<td style=\"width: 100%;\">\r\n<p>Dear Admin.&nbsp;</p>\r\n<p>New User [userName]&nbsp; trying to contact you</p>\r\n<p>Users Details are</p>\r\n<p>Email :&nbsp; [userEmail]</p>\r\n<p>Phone&nbsp; :&nbsp; [telephone]</p>\r\n<p>Meaasge : [message]</p>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>', 1, 0, '2018-02-14 00:00:00', 0, '2018-02-14 09:04:32', tblprfx_),
(NULL, 'reset-password', 'Save Reset Password!', 'Save Reset Password!', '<div style=\"max-width: 700px; min-width: 270px; margin: 0 auto; border: solid 2px #fff;\">\r\n<table style=\"padding: 15px; background-color: #[primary_color]; border-bottom: solid 5px #[secondary_color];\" border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\">\r\n<h1 style=\"color: #222; font-size: 23px; font-weight: 400; margin: 11px 13px 11px;\">Dear [firstName],</h1>\r\n</td>\r\n<td align=\"right\"><a href=\"[web_url]\" target=\"_blank\" rel=\"noopener\"><img src=\"[logoPath]\" /></a></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<div style=\"padding: 0px; font-family: Arial, Helvetica, sans-serif; color: #484848; font-size: 12px; line-height: 19px; height: auto;\">\r\n<div style=\"width: 100%; display: table;\">\r\n<div style=\"font-family: sans-serif; color: #333333; text-align: left; font-size: 13px;\">\r\n<h4 style=\"font-weight: normal;\">Your new password for the&nbsp; [email] has been set.</h4>\r\n</div>\r\n</div>\r\n<div style=\"padding: 20px 0px 0px 0px;\"><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">Regards,</strong><br /><strong style=\"font-family: Source Sans Pro,Geneva,sans-serif;\">[storeName]</strong></div>\r\n<br />\r\n<div style=\"font-family: sans-serif; color: #222; background: #ececec; padding: 12px; text-align: center; font-size: 13px; border-top: solid 1px #6b6b6b;\"><span style=\"font: \'Arial Black\', Gadget, sans-serif;\">Visit Us <a style=\"color: #222;\" href=\"[web_url]\" target=\"_blank\" rel=\"noopener\">[web_url]</a></span></div>\r\n</div>\r\n</div>', 1, 1, '2018-07-26 00:00:00', 1, '2018-07-26 08:26:12', tblprfx_);
INSERT INTO `flags` (`id`, `flag`, `value`, `desc`, `status`, `store_id`) VALUES
(NULL, 'Pending', '#3D4FFF', 'Orders marked blue are pending', 1, tblprfx_),
(NULL, 'Important', '#FF0000', 'Orders marked red are important', 1, tblprfx_),
(NULL, 'Closed', '#1EB800', 'Orders marked Green are important', 1, tblprfx_);
INSERT INTO `general_setting` (`id`, `name`, `status`, `details`, `url_key`, `type`, `sort_order`, `is_active`, `is_question`, `question_category_id`,`info`, `store_id`) VALUES
(NULL, 'Would you like to offer "Loyalty Program"?', 1, '', 'loyalty', 1, 89, 1, 1, 1,'This feature allows you to create multiple loyalty groups. To each group you can assign the percentage of Loyalty Points you wish to every time they shop. Also, it allows you to set the limit for the days after which the discount will be applied and showed to the customer in their account. After which these points can be used by the customer in future shopping giving them benefit of discount. More they more discounts they can get.', tblprfx_),
(NULL, 'Would you like to offer "Referral Program"?', 1, '{"activate_duration_in_days":"10","bonous_to_referee":"2","discount_on_order":"5"}', 'referral', 3, 88, 1, 0, 1,'This feature allows sending the Referral code to the customer while registering on the website for the first time. The cod is sent via SMS and email to their registered Mobile and Email id. Customers can share this code with their friends. The shared code can be used by their friends while placing the order to get the benefit of the Referral discount. Also, it allows you to choose the number of days after which the referral points will get activated. It also allows you to set the percentage of discount which will be received by the Referral (one who shares the code) and the Referee (one who applies the code).', tblprfx_),
(NULL, 'Do you want to use "System Users"? Multiple admins with different roles can be created', 1, '', 'acl', 1, 3, 1, 0, 2,'This feature helps you to create multiple users for accessing the store admin. This access can be restricted by assigning the user their specific roles or the information that they can access.', tblprfx_),
(NULL, 'Ebs', 0, '{"mode":"TEST","account_id":"5880","key":"ebskey"}', 'ebs', 2, NULL, 0, 0, 0,'', tblprfx_),
(NULL, 'Paypal', 1, '{"mode":"sandbox","api_username":"madhuriy411_api1.gmail.com","api_password":"LJ9D7PANGH7L2AVH","api_signature":"AkqgSqqB.3FWMu7CCj7GPtu6rrpoAmIk.o5xX2JhImzD58jQ4BesOpc0","currency_code":"USD","logo_url":"sdfsdfdfgfdg"}', 'paypal', 2, NULL, 0, 0, 0,'', tblprfx_),
(NULL, 'PayUmoney', 1, '{"merchant_id":"gtKFFx","salt":"eCwWELxi"}', 'pay-u-money', 2, NULL, 0, 0, 0,'', tblprfx_),
(NULL, 'Razorpay', 1, '{ 	"merchant_name": "Test", 	"key": "rzp_test_su8bbxUKo3wHYG", 	  "logo":"" }', 'razorpay', 2, NULL, 0, 0, 0,'', tblprfx_),
(NULL, 'Citrus Pay', 1, '{"post_url":"https:\\/\\/sandbox.citruspay.com\\/sslperf\\/o0c4dxl6ck","secret_key":"beeef7dae541c87a6497ec5e5843b359c1f7eb66","vanity_url":"o0c4dxl6ck"}', 'citrus', 2, NULL, 0, 0, 0,'', tblprfx_),
(NULL, 'Do you offer "Cash on Delivery" option?', 1, '{"charges":"25"}', 'cod', 1, 90, 1, 1, 3,'The Cash on Delivery (COD) feature allows the customer to pay for the goods at the time of delivery at their footstep. You can charge extra amount in COD, if needed. If you do not wish to charge extra to your customers for COD facility write ‘0’ (zero) in the popup.', tblprfx_),
(NULL, 'Would you like to use "Coupons" codes to offer discounts?', 1, '', 'coupon', 1, 7, 1, 1, 1,'This feature allows you to create Coupons/discount codes. You can also create coupon codes specific to a user. Coupon codes can be fixed or in percentage.', tblprfx_),
(NULL, 'Mandrill', 1, '{"key":"YScTkmt11OtZ39I0sNRnYw","from":"noreply@cartini.com","name":"Cartini"}', 'mandrill', 4, NULL, 0, 0, 0,'', tblprfx_),
(NULL, 'SMTP', 1, '{"host":"smtp.gmail.com","port":"587","from":"madhuri@infiniteit.biz","name":"cartini","encryption":"tls","username":"support@infiniteit.biz","password":"asdf1234"}', 'smtp', 4, NULL, 0, 0, 0,'', tblprfx_),
(NULL, 'Would you like to send Push Notification to the Customers for any Sales Promotion, etc?', 0, '', 'notification', 1, 2, 0, 0, 2,'This feature allows you send push notifications to the customers using the mobile app.', tblprfx_),
(NULL, 'Register Template', 1, '', 'register-template', 5, NULL, 0, 0, 0,'', tblprfx_),
(NULL, 'Success Template', 1, '', 'success-template', 5, NULL, 0, 0, 0,'', tblprfx_),
(NULL, 'Do you want to use product marked "Barcodes" OR "System Generated Barcode" in product detail? ', 0, '', 'barcode', 1, 9, 1, 1, 2,'This feature allows you to use barcodes that product already has or even the system can generate unique barcodes for every product.', tblprfx_),
(NULL, 'Product Return Days after it is delivered', 1, '5', 'product-return-days', 6, NULL, 0, 0, 0,'', tblprfx_),
(NULL, 'Do you want to send Invoice details to the customers via email automatically?', 0, '{"storename":"cartini"}', 'invoice', 1, 2, 0, 0, 2,'This feature sends invoice copy to customers automatically when an order is placed on their registered email id.', tblprfx_),
(NULL, 'Stock', 1, '{"stock_limit":"10"}', 'stock-old', 7, NULL, 0, 0, 0,'', tblprfx_),
(NULL, 'Do you want to avail Pincode based option of enabling/disabling deliveries + applying Shipping Charges as per Pincodes?', 0, '', 'pincode', 1, 11, 1, 0, 2,'This feature helps to store owner to restrict users from marked Pincodes to place the order. System will accept only orders which pincodes are enabled in Pincodes under Settings tab in left menu.', tblprfx_),
(NULL, 'Do you want to maintain purchase records on the platform?', 0, '', 'purchase', 1, 12, 0, 0, 4,'This feature allows you to capture your purchase information.', tblprfx_),
(NULL, 'Do you want to manage "Inventory"?', 0, '{"stocklimit":"10"}', 'stock', 1, 13, 1, 0, 4,'This feature helps you to maintain the Inventory of the products. It helps to edit/update the stock of the product. Even the minimum stock limit can be set here so that if the stock goes beyond that number it shows in Running Short or Out of Stock section.', tblprfx_),
(NULL, 'Do you want this Admin panel in multi language?', 0, '', 'multi-language', 0, 14, 0, 0, 2,'This feature helps to have the admin in multi-language. For this to work the owner has to define the language and then has to add all the translated word in that language in the Language Translation in the left menu.', tblprfx_),
(NULL, 'Do you want to use "Taxes"? Are your products inclusive/exclusive of taxes?', 0, '', 'tax', 1, 15, 1, 1, 2,'This feature allows you to add Taxes. You can apply taxes to your products either by including the tax amount in the product price (Inclusive) or by assigning it separately (Exclusive).', tblprfx_),
(NULL, 'set_popup', 1, '', '', 0, NULL, 1, 0, 0,'This feature is for developers of the platform to identity the bugs/error occurred.', tblprfx_),
(NULL, 'Do you have products with Variants? ', 0, '', 'products-with-variants', 1, 16, 1, 1, 5,'This feature allows you to have configurable products/products with variants on the website. Variants are the for example color, sizes etc. Every Variant has multiple Attributes. For example Color variant will have attributes Red, Yellow, and Blue etc. and Size variant will have attributes like Small, Medium, Large etc.', tblprfx_),
(NULL, 'Do you want to use table management facility?', 1, '', 'do-you-want-to-use-table-management-facility', 1, 16, 1, 1, 2,'', tblprfx_),
(NULL, 'Do you want to capture your "Raw Material" information?', 0, '', 'row-material', 1, 16, 0, 0, 2,'This feature allows you to capture your raw material information. Raw Materials is under Products tab in the left menu', tblprfx_),
(NULL, 'Would you like to use "Flags" under orders?', 1, '', 'flag', 0, 17, 1, 0, 2,'This feature allows you to flag/mark the orders for internal references. Orders can be flagged and marked by assigning the colors like Red, Blue, Green, Yellow etc. or assigning the statuses like Important, Pending etc. to it.', tblprfx_),
(NULL, 'Is this a Marketplace?', 0, '', 'market-place', 0, 24, 0, 0, 2,'A marketplace (or online e-commerce marketplace) is a type of e-commerce website where products are provided by multiple third parties, whereas transactions are processed by the marketplace owner. It gives option to add vendors and products that they offer.', tblprfx_),
(NULL, 'Do you want to show "Additional Description" in product detail?', 0, '', 'des', 0, 50, 1, 0, 5,'This feature allows you to show additional detailed description against every product on the product detail page.', tblprfx_),
(NULL, 'Do you want to show "Testimonials"?', 1, '', 'testimonial', 1, 27, 1, 0, 2,'This feature allows you to show the Testimonials (feedback of your customers) on the website. It has options to add picture, name, comment etc. of the customer.', tblprfx_),
(NULL, 'Do you want to show "Related Products" on product detail?', 1, '', 'related-products', 1, 28, 1, 1, 5,'This feature allows you to mark products under ‘Related Products’ section on the product detail page of the website. You can mark the products which are similar to the product or the products that you would like to cross-sell. You can mark the related products according to the category/ variant/attributes etc.', tblprfx_),
(NULL, 'Do you want to show "You may also like" products on product detail?', 0, '', 'like-product', 1, 31, 1, 0, 5,'This feature allows you to mark products under ‘You may also like’ section on the product detail page of the website. You can mark the products which are similar to the product or the products that you would like to cross-sell.', tblprfx_),
(NULL, 'Do you want to use Email facility?', 1, '', 'email-facility', 1, 0, 1, 0, 1,'This feature allows system to send emails to customers on their registered email ids for order placed, order dispatched, order cancelled/returned etc', tblprfx_),
(NULL, 'Do you want to set debug option true?', 0, '', 'debug-option', 0, 70, 0, 0, 1,'', tblprfx_),
(NULL, 'Would you want to add discount manually while placing order on the app?', 0, '', 'manual-discount', 1, 32, 1, 1, 2,'This feature allows the users and store owner to add manual discount while placing the order on the checkout page.', tblprfx_),
(NULL, 'Would you like to use the Return Order facility?', 0, '', 'return-product', 1, 34, 1, 1, 2,'This feature allows the customer to return their delivered order by mentioning the reason why they wish to return the order. They can only return if this feature is marked Yes', tblprfx_),
(NULL, 'Do you want to use Courier Service to deliver products to the customers?', 0, 'courier services like fedex deliveru blue dart', 'courier-services', 1, NULL, 0, 0, 2,'Mark this features ‘Yes’ if you wish to use the courier service synced with the platform. Mark it ‘No’ if you wish to courier goods by yourself.', tblprfx_),
(NULL, 'question_category_id', 1, '', 'question_category_id', 1, 21, 1, 0, 0,'', tblprfx_),
(NULL, 'Would you like to use "Additional Charges" feature?', 0, '', 'additional-charge', 0, 95, 1, 0, 2,'The Additional Charges feature allows you to create your own custom charges which will be applied against every order. For example: Transport Charges, Handling Charges etc. These charges can be fixed or in percentage. Additional Charges feature is under Orders in the left menu.', tblprfx_),
(NULL, 'Would you like to use "Dimention Details" in product detail?', 0, '', 'product-daimention', 1, 21, 1, 0, 0,'This feature allows you to add dimentions of the product on product detail page. Dimensions here can be Length, Width, Height and Weight.', tblprfx_),
(NULL, 'Would you like to use "Minimum Order Quantity"?', 0, '', 'minimum-order', 0, 25, 0, 0, 5,'', tblprfx_),
(NULL, 'Would you like to use "SEO (Search Engine Optimization)"?', '0', '', 'sco', '1', '12', '1', '0', '1','SEO (Search Engine Optimization) helps to increase the online visibility of a website and its products in the web search engines like Google', tblprfx_),
(NULL, 'Would you like to use "Guest Checkout" feature?', 1, '', 'guest-checkout', 1, 23, 1, 0, 0,'This feature allows customer to checkout without logging in/registering on the website. Only email is asked from the customer for future communication.', tblprfx_),
(NULL, 'Bank Account Details', '1', '{\"bank_name\":\"bank_name \",\"branch_name\":\"branch_name\",\"ifsc\":\"ifsc\",\"bank_address\":\"asdf sdff sdf asdfa sdfa dfa dasd asdf asdfa dfad asdf asdfa dfa sda d\",\"city\":\"mum\",\"state\":\"1504\",\"country\":\"99\",\"acc_type\":\"1\",\"acc_no\":\"123123123123123123123\"}', 'bank_acc_details', '8', '1', '1', '0', '3', 'Bank account information.', tblprfx_),
(NULL,'would you like to use default courier services provided by eStorifi', 1,'', 'default-courier', 1, 12, 1, 1, 2, 'Only when eStorifi Logistic Partner service is used, delivery of the Order and COD (Cash On Delivery) will be managed by eStorifi. These payments will be settled to the Merchant’s bank account within Transaction + 2 working days. The amount transferred will be Amount Transferred = Transaction Amount - Shipping Charges - eStorifi Commission. If Merchant uses his/her own logistic partner, the Merchant will be responsible for delivery of the Order and COD (Cash On Delivery)', tblprfx_);
INSERT INTO `language` (`id`, `name`, `status`, `store_id`) VALUES
(NULL, 'Hindi', 1, tblprfx_),
(NULL, 'English', 1, tblprfx_),
(NULL, 'Bengali', 1, tblprfx_);
INSERT INTO `layout` (`id`, `name`, `url_key`, `is_active`, `is_del`, `store_id`) VALUES
(NULL, 'Home Page Slider', 'home-page-slider', 1, 0, tblprfx_),
(NULL, 'Home Page 3 Boxes', 'home-page-3-boxes', 1, 0, tblprfx_);
INSERT INTO `loyalty` (`id`, `group`, `min_order_amt`, `max_order_amt`, `percent`, `range_amt`, `status`, `store_id`) VALUES
(NULL, 'Silver', 2000, 5000, 2, '2000 - 5,000', 1, tblprfx_),
(NULL, 'Gold', 5001, 10000, 5, '5,001 - 10,000', 1, tblprfx_),
(NULL, 'Platinum', 10001, 100000, 10, 'Above 10,001', 1, tblprfx_);
INSERT INTO `offers` (`id`, `offer_name`, `offer_discount_type`, `offer_type`, `offer_discount_value`, `min_order_qty`, `min_free_qty`, `min_order_amt`, `max_discount_amt`, `max_usage`, `actual_usage`, `full_incremental_order`, `start_date`, `end_date`, `user_specific`, `status`, `store_id`) VALUES
(NULL, 'Buy 2 get 20%off on 3rd product onwards', 1, 1, 20, 2, 0, 5000, 500, 0, 0, 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 0, 0, tblprfx_);
INSERT INTO `order_return_action` (`id`, `action`, `store_id`) VALUES
(NULL, 'Credit Issued', tblprfx_),
(NULL, 'Refunded', tblprfx_),
(NULL, 'No Action', tblprfx_);
INSERT INTO `order_return_open_unopen` (`id`, `status`, `store_id`) VALUES
(NULL, 'Opened', tblprfx_),
(NULL, 'Unopened', tblprfx_);
INSERT INTO `order_status` (`id`, `order_status`, `status`,`sort_order`, `store_id`) VALUES
(NULL, 'Processing', 1,1, tblprfx_),
(NULL, 'Shipped', 1,2, tblprfx_),
(NULL, 'Delivered', 1,3, tblprfx_),
(NULL, 'Cancelled', 1,4, tblprfx_),
(NULL, 'Exchanged', 1,5, tblprfx_),
(NULL, 'Returned', 1,6, tblprfx_),
(NULL, 'Undelivered', 1,7, tblprfx_),
(NULL, 'Delayed', 1,8, tblprfx_),
(NULL, 'Partially Shipped', 1,9, tblprfx_),
(NULL, 'Refunded', 1,10, tblprfx_);
INSERT INTO `pincodes` (`id`, `pincode`, `cod_status`, `service_provider`, `pref`, `status`, `store_id`) VALUES
(NULL, '400022', 0, 1, 1, 1, tblprfx_),
(NULL, '400021', 1, 1, 1, 1, tblprfx_),
(NULL, '400023', 0, 1, 1, 1, tblprfx_),
(NULL, '400024', 0, 1, 1, 1, tblprfx_),
(NULL, '400025', 0, 2, 2, 1, tblprfx_),
(NULL, '400026', 1, 2, 2, 1, tblprfx_),
(NULL, '400027', 1, 2, 2, 1, tblprfx_),
(NULL, '789456', 0, 3, 3, 1, tblprfx_),
(NULL, '789654', 0, 3, 3, 1, tblprfx_),
(NULL, '789456', 0, 3, 3, 1, tblprfx_);
INSERT INTO `products` (`id`, `product`, `product_code`, `alias`, `short_desc`, `long_desc`, `add_desc`, `is_featured`, `images`, `prod_type`, `is_stock`, `attr_set`, `url_key`, `is_avail`, `is_listing`, `status`, `stock`, `cur`, `max_price`, `min_price`, `purchase_price`, `price`, `unit_measure`, `consumption_uom`, `conversion`, `height`, `width`, `length`, `weight`, `spl_price`, `selling_price`, `is_crowd_funded`, `target_date`, `target_qty`, `parent_prod_id`, `meta_title`, `meta_keys`, `meta_desc`, `art_cut`, `is_cod`, `added_by`, `updated_by`, `is_individual`, `sort_order`, `meta_robot`, `canonical`, `og_title`, `og_desc`, `og_image`, `twitter_url`, `twitter_title`, `twitter_desc`, `twitter_image`, `og_url`, `other_meta`, `is_referal_discount`, `is_shipped_international`, `eCount`, `eNoOfDaysAllowed`, `barcode`, `is_tax`, `is_del`, `min_order_quantity`, `is_trending`, `store_id`) VALUES
(NULL, 'Men Green Printed Custom Fit Polo Collar T-shirt', '', '', '', '', '', 0, '/tmp/phpFCjDcZ', 1, 1, 1, 'men-green-printed-custom-fit-polo-collar-t-shirt', 1, 0, 1, 100, '', 0, 0, '0.00', '200173.54', '', '', '0.00', 0, 0, 0, 0, '120077.43', '120077.43', 0, '0000-00-00 00:00:00', 0, 0, '', '', '', 0, 1, 1, 1, 1, 0, '', '', '', '', '', '', '', '', '', '', '', 0, 0, 0, 0, '', 0, 0, 1, 1, tblprfx_);
INSERT INTO `product_types` (`id`, `type`, `type_id`, `desc`, `status`, `store_id`) VALUES
(NULL, 'Simple', 1, '', 1, tblprfx_),
(NULL, 'Combo', 2, '', 0, tblprfx_),
(NULL, 'Configurable', 3, '', 1, tblprfx_),
(NULL, 'Configurable Without Stock', 4, '', 0, tblprfx_),
(NULL, 'Downloadable Product', 5, 'Downloadable Product', 0, tblprfx_),
(NULL, 'Raw Material/Non Saleable', 6, '', 0, tblprfx_),
(NULL, 'Simple Without Stock', 7, '', 0, tblprfx_);
INSERT INTO `roles` (`id`, `name`, `display_name`, `description`,`store_id`) VALUES
(null, 'admin', 'Admin', 'This is the admin who has access to complete system.', tblprfx_),
(null, 'operator-manager', 'Operator/Manager', 'This is operator/manager role. You can change the viewing rights by editing it.', tblprfx_),
(null, 'sales-marketing', 'Sales/Marketing', 'This is sales/marketing user who has access to only Orders and Products. You can change the viewing rights by editing it.', tblprfx_);

INSERT INTO `slider_master` (`id`, `slider`, `is_active`, `delete_master`, `store_id`) VALUES
(NULL, 'main', '1', '0', tblprfx_),
(NULL, 'SiderBar', '0', '1', tblprfx_),
(NULL, 'SiderBar', '0', '1', tblprfx_),
(NULL, 'Footer Slider', '0', '0', tblprfx_),
(NULL, 'Sidebar', '0', '0', tblprfx_),
(NULL, 'cvcvcvc', '1', '0', tblprfx_);
INSERT INTO `social_media_links` (`id`, `media`, `link`, `image`, `status`, `sort_order`, `store_id`) VALUES
(NULL, 'facebook', 'https://www.facebook.com/', '16082017120616.png', 1, 0, tblprfx_),
(NULL, 'instagram', 'https://www.instagram.com/', '15022018095403.jpg', 1, 0, tblprfx_),
(NULL, 'twitter', 'https://twitter.com/', '23022018093140.png', 1, 0, tblprfx_),
(NULL, 'google', 'https://plus.google.com/', '26022018091609.jpg', 1, 0, tblprfx_),
(NULL, 'linkedin', 'https://www.linkedin.com/', '08032018065004.png', 1, 0, tblprfx_),
(NULL, 'youtube', 'https://www.youtube.com/', '21062018121043.jpg', 1, 0, tblprfx_);
INSERT INTO `static_pages` (`id`, `page_name`, `url_key`, `image`, `description`, `map_url`, `email_list`, `link`, `status`, `is_menu`, `contact_details`, `sort_order`, `store_id`) VALUES
(NULL, 'About Us', 'about-us', '23062018113857.jpg', 'Your Store Name&nbsp;about page is an opportunity to tell a story that will help you to stick in your customer&rsquo;s minds. You can describe your History, Vision &amp; Mission, and Your Global Presence etc. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. &nbsp; Lorem ipsum dolor sit amet&nbsp; Duis aute irure dolor in reprehenderit Quis autem vel eum voluptate &nbsp; Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.\r\n', '', '', '', 1, 1, 'null', 1, tblprfx_),
(NULL, 'Terms and Condition', 'terms-conditions', '', 'For the purpose of these Terms &amp; Conditions, wherever the context so requires &quot;You&quot; or &quot;User&quot; shall mean any natural or legal person who has agreed to become a buyer on the Website by providing Registration Data while registering on the Website as Registered User using the computer systems. &ldquo;Website URL&rdquo; allows the User to surf the Website or making purchases without registering on the Website. The term &quot;We&quot;, &quot;Us&quot;, &quot;Our&quot; shall mean &ldquo;Store Name&rdquo;.\r\n\r\nWhen You use any of the services provided by Us through the Website, including but not limited to, (e.g. Product Images, Testimonials), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms &amp; Conditions and shall be considered as part and parcel of this Terms &amp; Conditions.&nbsp;\r\n\r\nWe reserve the right, at our sole discretion, to change, modify, add or remove portions of these Terms &amp; Conditions , at any time without any prior written notice to you. It is your responsibility to review these Terms &amp; Conditions periodically for updates / changes. Your continued use of the Website following the posting of changes will mean that you accept and agree to the revisions. As long as you comply with these Terms &amp; Conditions, We grant you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.\r\n\r\nACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS AND CONDITIONS, SO PLEASE READ THE TERMS AND CONDITIONS CAREFULLY BEFORE PROCEEDING.\r\n', '', '', '', 1, 0, 'null', 3, tblprfx_),
(NULL, 'Privacy Policy', 'privacy-policy', NULL, '&nbsp;\r\n\r\nThis privacy notice discloses the privacy practices for (website address). This privacy notice applies solely to information collected by this website. It will notify you of the following:\r\n\r\n\r\n\r\n	What personally identifiable information is collected from you through the website, how it is used and with whom it may be shared.\r\n	What choices are available to you regarding the use of your data\r\n	The security procedures in place to protect the misuse of your information.\r\n	How you can correct any inaccuracies in the information.\r\n\r\n\r\n\r\nInformation Collection, Use, and Sharing&nbsp;\r\n\r\nWe are the sole owners of the information collected on this site. We only have access to/collect information that you voluntarily give us via email or other direct contact from you. We will not sell or rent this information to anyone.\r\n\r\nWe will use your information to respond to you, regarding the reason you contacted us. We will not share your information with any third party outside of our organization, other than as necessary to fulfill your request, e.g. to ship an order.\r\n\r\nUnless you ask us not to, we may contact you via email in the future to tell you about specials, new products or services, or changes to this privacy policy.\r\n\r\n&nbsp;\r\n\r\nYour Access to and Control Over Information&nbsp;\r\n\r\nYou may opt out of any future contacts from us at any time. You can do the following at any time by contacting us via the email address or phone number given on our website:\r\n\r\n\r\n\r\n	See what data we have about you, if any.\r\n	Change/correct any data we have about you.\r\n	Have us delete any data we have about you.\r\n	Express any concern you have about our use of your data.\r\n\r\n\r\n\r\nSecurity&nbsp;\r\n\r\nWe take precautions to protect your information. When you submit sensitive information via the website, your information is protected both online and offline.\r\n\r\nWherever we collect sensitive information (such as credit card data), that information is encrypted and transmitted to us in a secure way. You can verify this by looking for a lock icon in the address bar and looking for &quot;https&quot; at the beginning of the address of the Web page.\r\n\r\nWhile we use encryption to protect sensitive information transmitted online, we also protect your information offline. Only employees who need the information to perform a specific job (for example, billing or customer service) are granted access to personally identifiable information. The computers/servers in which we store personally identifiable information are kept in a secure environment.\r\n\r\n&nbsp;\r\n\r\nIf you feel that we are not abiding by this privacy policy, you should contact us immediately via phone at 1234567890 or via email us at email@domain.com\r\n\r\n&nbsp;\r\n', '', '', '', 1, 0, 'null', 1, tblprfx_),
(NULL, 'Contact Us', 'contact-us', NULL, '<p>Vidyavihar West, Mumbai</p>\r\n', '', '', '', 1, 1, '{\"contact_person\":\"John Smith\",\"mobile\":\"09000012345\",\"email\":\"abc@gmail.com\",\"address_line1\":\"C\\/501,  Chocolate  Building\",\"address_line2\":\"Vanila Street\",\"Thana\":\"Ghatkoper\",\"city\":\"Mumbai\",\"country\":\"99\",\"state\":\"1493\",\"pincode\":\"400123\","map_url":"https:\/\/www.google.com\/maps\/embed?pb=!1m18!1m12!1m3!1d3770.6811444007703!2d72.90397851490121!3d19.07775178708691!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7c62f40000039%3A0xe11790fc65fd4052!2sInfini+Systems+Pvt+Ltd!5e0!3m2!1sen!2sin!4v1503846275179"}', 4, tblprfx_);
INSERT INTO `store_settings` (`id`, `name`, `value`, `url_key`, `store_id`) VALUES
(NULL, 'ACL', 'No', 'acl', tblprfx_);
INSERT INTO `tax` (`id`, `type`, `name`, `label`, `rate`, `tax_number`, `status`, `store_id`) VALUES
(NULL, 0, 'VAT', 'VAT', 10.00, 'ABCD1234', 0, tblprfx_),
(NULL, 0, 'GST', 'GST', 18.00, '22ABCDE1234F2Z5', 0, tblprfx_);
INSERT INTO `testimonials` (`id`, `user_id`, `image`, `customer_name`, `testimonial`, `gender`, `sort_order`, `status`, `store_id`) VALUES
(NULL, 1, '21062018122049.jpg', 'Rini Shah, eStorifi', 'Incidunt deleniti blanditiis quas aperiam recusandae consequatur ullam quibusdam cum libero illo rerum!', 'female', 3, 1, tblprfx_),
(NULL, 1, '21062018121817.jpg', 'John Doe, Abc Ltd.', 'Porro dolorem saepe reiciendis nihil minus neque. Ducimus rem necessitatibus repellat laborum nemo quod.', 'male', 2, 1, tblprfx_),
(NULL, 1, '21062018121742.jpg', 'Steve Jobs, Apple Inc.', 'Similique fugit repellendus expedita excepturi iure perferendis provident quia eaque. Repellendus, vero numquam.', 'male', 1, 1, tblprfx_);
INSERT INTO `unit_measures` (`id`, `unit`, `status`, `store_id`) VALUES
(NULL, 'Meter', 1, tblprfx_),
(NULL, 'Centimeter', 1, tblprfx_);
UPDATE `general_setting` SET `status` = '1' WHERE `general_setting`.`id` in (13,50);
